// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0NZ8ICrNhoVulhijCNvN-C66ZUzR6J3c',
    appId: '1:745446006332:web:0d4e4f9a47ca58cfdf6d39',
    messagingSenderId: '745446006332',
    projectId: 'careloom-f5186',
    authDomain: 'careloom-f5186.firebaseapp.com',
    storageBucket: 'careloom-f5186.firebasestorage.app',
    measurementId: 'G-JF8JQ6D052',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfFCoRJEEaNZLo6cqUrZXzzh4SwL9neSc',
    appId: '1:745446006332:android:2a09e2c601fa2c8ddf6d39',
    messagingSenderId: '745446006332',
    projectId: 'careloom-f5186',
    storageBucket: 'careloom-f5186.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnG9QLvmP7VwuZLFlZZ8_7uIiMqX6AiyY',
    appId: '1:745446006332:ios:c2f02f3234c40e89df6d39',
    messagingSenderId: '745446006332',
    projectId: 'careloom-f5186',
    storageBucket: 'careloom-f5186.firebasestorage.app',
    iosBundleId: 'com.example.careLoomApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnG9QLvmP7VwuZLFlZZ8_7uIiMqX6AiyY',
    appId: '1:745446006332:ios:c2f02f3234c40e89df6d39',
    messagingSenderId: '745446006332',
    projectId: 'careloom-f5186',
    storageBucket: 'careloom-f5186.firebasestorage.app',
    iosBundleId: 'com.example.careLoomApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0NZ8ICrNhoVulhijCNvN-C66ZUzR6J3c',
    appId: '1:745446006332:web:1a301f42dc00e96adf6d39',
    messagingSenderId: '745446006332',
    projectId: 'careloom-f5186',
    authDomain: 'careloom-f5186.firebaseapp.com',
    storageBucket: 'careloom-f5186.firebasestorage.app',
    measurementId: 'G-16GY95WZ34',
  );

}